# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.9
      - name: Install pipenv
        run: pip install pipenv
      - name: Enter backend folder
        run: cd backend
      - name: Install Packages
        run: pipenv install
      - name: Start Virtual Environment
        run: pipenv shell
      - name: Test Backend
        run: python testing.py
