# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install pipenv
        run: pip install pipenv
      - name: Enter backend folder and run tests
        run: |
          cd backend
          pipenv install
          pipenv shell
          python testing.py
