# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.9
      - name: Install pipenv
        run: pip install pipenv
      - name: Go into backend folder, create virtual environent, and run testing
        run: |
          cd backend
          pipenv install
          pipenv run python testing.py